# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: npminstall
  steps:
  - script: npm install

- job: npmrunlint
  dependsOn: npminstall
  condition: succeeded()
  steps:
  - script: npm run lint

- job: npmrunbuild
  dependsOn: npmrunlint
  condition: succeeded()
  steps:
  - script: npm run build

  displayName: 'Lint and Build'
