//Product list
export const GET_PRODUCTS_REQUEST='GET_POSTS_REQUEST';
export const GET_PRODUCTS_SUCCESS='GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE='GET_PRODUCTS_FAILURE';

//Customer list
export const GET_CUSTOMERS_REQUEST='GET_CUSTOMERS_REQUEST';
export const GET_CUSTOMERS_SUCCESS='GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_FAILURE='GET_CUSTOMERS_FAILURE';
